<?php

namespace AnagraficheBundle\Repository;

/**
 * aggiungi_personeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aggiungi_personeRepository extends \Doctrine\ORM\EntityRepository
{
}
