<?php

namespace AnagraficheBundle\Repository;

/**
 * nuovo_clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nuovo_clienteRepository extends \Doctrine\ORM\EntityRepository
{
}
