pacchetti:
    resource: "@PacchettiBundle/Resources/config/routing.yml"
    prefix:   /pacchetti

anagrafiche:
    resource: "@AnagraficheBundle/Resources/config/routing.yml"
    prefix:   /anagrafiche

entrate:
    resource: "@EntrateBundle/Controller/"
    type:     annotation
    prefix:   /entrate

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /stampa
    
