<?php

namespace PacchettiBundle\Repository;

/**
 * nuovo_pacchettoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nuovo_pacchettoRepository extends \Doctrine\ORM\EntityRepository
{
}
