<?php

namespace PacchettiBundle\Repository;

/**
 * serviziRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviziRepository extends \Doctrine\ORM\EntityRepository
{
}
