crea_Pacchetto:
    path:  /crea
    defaults: { _controller: PacchettiBundle:Pacchetti:index }
lista_Pacchetto:
    path:  /lista
    defaults: { _controller: PacchettiBundle:Pacchetti:view }
modifica_pacchetto:
    path:  /pacchetto/{id}/edit
    defaults: { _controller: PacchettiBundle:Pacchetti:editpacchetti }


    
