<?php

namespace EntrateBundle\Repository;

/**
 * entrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrateRepository extends \Doctrine\ORM\EntityRepository
{
}
