<?php

namespace EntrateBundle\Repository;

/**
 * wonderfulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wonderfulRepository extends \Doctrine\ORM\EntityRepository
{
}
